import jsPDF from "jspdf";
import { AnalysisResult } from "@/types";

// ── Colour palette (dark theme translated to print-friendly)
const C = {
  bg: [8, 13, 26] as [number, number, number],
  bgCard: [13, 23, 42] as [number, number, number],
  border: [30, 42, 58] as [number, number, number],
  white: [232, 240, 255] as [number, number, number],
  muted: [100, 120, 160] as [number, number, number],
  blue: [59, 130, 246] as [number, number, number],
  emerald: [34, 197, 148] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  orange: [249, 115, 22] as [number, number, number],
};

function scoreColor(s: number): [number, number, number] {
  if (s >= 80) return C.emerald;
  if (s >= 60) return C.amber;
  if (s >= 40) return C.orange;
  return C.red;
}

function severityColor(sev: string): [number, number, number] {
  if (sev === "critical") return C.red;
  if (sev === "warning") return C.amber;
  return C.blue;
}

function formatMs(ms: number) {
  return ms > 1000 ? `${(ms / 1000).toFixed(1)}s` : `${Math.round(ms)}ms`;
}

// Draw a filled rounded rectangle
function roundRect(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
  fillColor: [number, number, number],
  strokeColor?: [number, number, number],
) {
  doc.setFillColor(...fillColor);
  if (strokeColor) {
    doc.setDrawColor(...strokeColor);
    doc.roundedRect(x, y, w, h, r, r, "FD");
  } else {
    doc.roundedRect(x, y, w, h, r, r, "F");
  }
}

// Draw a score ring using arc approximation
function drawScoreRing(
  doc: jsPDF,
  cx: number,
  cy: number,
  r: number,
  score: number,
  label: string,
) {
  const color = scoreColor(score);
  // Track
  doc.setDrawColor(...C.border);
  doc.setLineWidth(2.5);
  doc.circle(cx, cy, r, "S");
  // Arc (score portion) — draw as many small line segments
  doc.setDrawColor(...color);
  doc.setLineWidth(2.5);
  const total = 100;
  const steps = Math.round((score / total) * 60);
  const startAngle = -Math.PI / 2;
  for (let i = 0; i < steps; i++) {
    const a1 = startAngle + (i / 60) * 2 * Math.PI;
    const a2 = startAngle + ((i + 1) / 60) * 2 * Math.PI;
    doc.line(
      cx + r * Math.cos(a1),
      cy + r * Math.sin(a1),
      cx + r * Math.cos(a2),
      cy + r * Math.sin(a2),
    );
  }
  // Score text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...color);
  doc.text(String(score), cx, cy + 3, { align: "center" });
  // Label
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...C.muted);
  doc.text(label, cx, cy + r + 7, { align: "center" });
}

// Page header with logo bar
function drawHeader(doc: jsPDF, url: string, date: string) {
  // Full-width header bar
  doc.setFillColor(...C.bgCard);
  doc.rect(0, 0, 210, 18, "F");
  doc.setFillColor(...C.blue);
  doc.roundedRect(8, 4, 10, 10, 1, 1, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  doc.text("S", 13, 10.5, { align: "center" });
  doc.setFontSize(10);
  doc.text("SiteScope", 22, 10.5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text(url, 105, 10.5, { align: "center" });
  doc.text(date, 202, 10.5, { align: "right" });
  // Bottom border
  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.line(0, 18, 210, 18);
}

// Page footer with page number
function drawFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const y = 290;
  doc.setDrawColor(...C.border);
  doc.setLineWidth(0.3);
  doc.line(8, y, 202, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.muted);
  doc.text("Generated by SiteScope — sitescope.dev", 8, y + 5);
  doc.text(`Page ${pageNum} of ${totalPages}`, 202, y + 5, { align: "right" });
}

export async function generatePDF(result: AnalysisResult): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210;
  const date = new Date(result.analyzedAt).toLocaleString();
  const lh = result.lighthouse;

  // ── PAGE 1: Cover + Overview ──────────────────────────────────────
  doc.setFillColor(...C.bg);
  doc.rect(0, 0, 210, 297, "F");
  drawHeader(doc, result.url, date);

  // Hero area
  let y = 28;

  // Overall score – large ring
  drawScoreRing(doc, 30, y + 22, 16, result.scores.overall, "Overall");

  // Title block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...C.white);
  doc.text("Website Audit Report", 56, y + 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.blue);
  doc.text(result.url, 56, y + 18);
  doc.setTextColor(...C.muted);
  doc.setFontSize(7.5);
  doc.text(`Analyzed: ${date}`, 56, y + 25);

  // Issue count pills
  const pills = [
    {
      label: `${result.issues.filter((i) => i.severity === "critical").length} Critical`,
      color: C.red,
    },
    {
      label: `${result.issues.filter((i) => i.severity === "warning").length} Warnings`,
      color: C.amber,
    },
    {
      label: `${result.issues.filter((i) => i.severity === "info").length} Info`,
      color: C.blue,
    },
  ];
  let px = 56;
  pills.forEach((pill) => {
    const tw = doc.getTextWidth(pill.label) + 6;
    roundRect(doc, px, y + 30, tw, 7, 1, [
      pill.color[0] * 0.15,
      pill.color[1] * 0.15,
      pill.color[2] * 0.15,
    ]);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...pill.color);
    doc.text(pill.label, px + 3, y + 35);
    px += tw + 4;
  });

  y += 52;

  // Summary box
  roundRect(doc, 8, y, W - 16, 22, 2, C.bgCard, C.border);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...C.blue);
  doc.text("EXECUTIVE SUMMARY", 14, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...C.white);
  const summaryLines = doc.splitTextToSize(result.summary, W - 28);
  doc.text(summaryLines.slice(0, 2), 14, y + 13);

  y += 30;

  // ── Category Score Grid ──────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.muted);
  doc.text("CATEGORY SCORES", 8, y + 5);
  y += 9;

  const scoreKeys: { key: keyof typeof result.scores; label: string }[] = [
    { key: "performance", label: "Performance" },
    { key: "seo", label: "SEO" },
    { key: "accessibility", label: "Accessibility" },
    { key: "security", label: "Security" },
    { key: "ux", label: "UX" },
    { key: "conversion", label: "Conversion" },
  ];

  const cardW = (W - 16 - 10) / 6;
  scoreKeys.forEach((sk, i) => {
    const cx = 8 + i * (cardW + 2) + cardW / 2;
    roundRect(doc, 8 + i * (cardW + 2), y, cardW, 34, 2, C.bgCard, C.border);
    drawScoreRing(doc, cx, y + 14, 8, result.scores[sk.key], sk.label);
  });

  y += 42;

  // ── Top Issues to Fix ─────────────────────────────────────────────
  if (result.topWins.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(...C.muted);
    doc.text("TOP ISSUES TO FIX", 8, y + 5);
    y += 9;

    result.topWins.forEach((win, i) => {
      roundRect(doc, 8, y, W - 16, 10, 1.5, C.bgCard, C.border);
      doc.setFillColor(...C.red);
      doc.rect(8, y, 2, 10, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      doc.setTextColor(...C.red);
      doc.text(`${i + 1}.`, 13, y + 6.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...C.white);
      doc.text(win, 19, y + 6.5);
      y += 13;
    });
  }

  // ── Lighthouse Metrics (if available) ────────────────────────────
  if (lh) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(...C.muted);
    doc.text("CORE WEB VITALS", 8, y + 5);
    y += 9;

    const metrics = [
      {
        label: "LCP",
        value: formatMs(lh.lcp),
        good: lh.lcp < 2500,
        warn: lh.lcp < 4000,
      },
      {
        label: "FCP",
        value: formatMs(lh.fcp),
        good: lh.fcp < 1800,
        warn: lh.fcp < 3000,
      },
      {
        label: "TBT",
        value: formatMs(lh.tbt),
        good: lh.tbt < 200,
        warn: lh.tbt < 600,
      },
      {
        label: "CLS",
        value: lh.cls.toFixed(3),
        good: lh.cls < 0.1,
        warn: lh.cls < 0.25,
      },
      {
        label: "TTI",
        value: formatMs(lh.tti),
        good: lh.tti < 3800,
        warn: lh.tti < 7300,
      },
      {
        label: "Speed Index",
        value: formatMs(lh.speedIndex),
        good: lh.speedIndex < 3400,
        warn: lh.speedIndex < 5800,
      },
    ];

    const mCardW = (W - 16 - 10) / 6;
    metrics.forEach((m, i) => {
      const mx = 8 + i * (mCardW + 2);
      const color = m.good ? C.emerald : m.warn ? C.amber : C.red;
      roundRect(doc, mx, y, mCardW, 20, 1.5, C.bgCard, C.border);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.5);
      doc.setTextColor(...C.muted);
      doc.text(m.label, mx + mCardW / 2, y + 7, { align: "center" });
      doc.setFontSize(9);
      doc.setTextColor(...color);
      doc.text(m.value, mx + mCardW / 2, y + 15, { align: "center" });
    });
    y += 28;
  }

  drawFooter(doc, 1, 2);

  // ── PAGE 2: All Issues ────────────────────────────────────────────
  doc.addPage();
  doc.setFillColor(...C.bg);
  doc.rect(0, 0, 210, 297, "F");
  drawHeader(doc, result.url, date);

  y = 26;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...C.white);
  doc.text("Issues & Recommendations", 8, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...C.muted);
  doc.text(`${result.issues.length} issues found`, 8, y + 7);
  y += 14;

  // Group by category for cleaner output
  const categories = [
    "Performance",
    "SEO",
    "Accessibility",
    "Security",
    "UX",
    "Conversion",
  ] as const;

  for (const cat of categories) {
    const catIssues = result.issues.filter((i) => i.category === cat);
    if (catIssues.length === 0) continue;

    // Check page space
    if (y > 258) {
      doc.addPage();
      doc.setFillColor(...C.bg);
      doc.rect(0, 0, 210, 297, "F");
      drawHeader(doc, result.url, date);
      y = 26;
    }

    // Category header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...C.blue);
    doc.text(cat.toUpperCase(), 8, y + 4);
    doc.setDrawColor(...C.border);
    doc.setLineWidth(0.3);
    doc.line(30, y + 3, W - 8, y + 3);
    y += 10;

    for (const issue of catIssues) {
      const sevColor = severityColor(issue.severity);
      // Estimate required height
      const descLines = doc.splitTextToSize(issue.description, W - 36);
      const fixLines = doc.splitTextToSize(`Fix: ${issue.fix}`, W - 36);
      const cardH = 8 + descLines.length * 4.5 + fixLines.length * 4.5 + 6;

      if (y + cardH > 272) {
        drawFooter(doc, doc.getNumberOfPages(), doc.getNumberOfPages());
        doc.addPage();
        doc.setFillColor(...C.bg);
        doc.rect(0, 0, 210, 297, "F");
        drawHeader(doc, result.url, date);
        y = 26;
      }

      // Card background
      roundRect(doc, 8, y, W - 16, cardH, 1.5, C.bgCard, C.border);
      // Severity left bar
      doc.setFillColor(...sevColor);
      doc.roundedRect(8, y, 2.5, cardH, 0.5, 0.5, "F");

      // Severity badge
      const badgeW = doc.getTextWidth(issue.severity) + 6;
      roundRect(doc, W - 16 - badgeW, y + 3, badgeW, 6, 1, [
        sevColor[0] * 0.15,
        sevColor[1] * 0.15,
        sevColor[2] * 0.15,
      ]);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6);
      doc.setTextColor(...sevColor);
      doc.text(issue.severity.toUpperCase(), W - 16 - badgeW / 2, y + 7, {
        align: "center",
      });

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(...C.white);
      doc.text(issue.title, 14, y + 8);

      // Description
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(...C.muted);
      doc.text(descLines, 14, y + 14);

      // Fix
      const fixY = y + 14 + descLines.length * 4.5 + 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(...C.emerald);
      doc.text("→ Fix:", 14, fixY);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...([180, 200, 230] as [number, number, number]));
      doc.text(fixLines, 28, fixY);

      y += cardH + 3;
    }

    y += 4;
  }

  // Update footer on last page
  const totalPages = doc.getNumberOfPages();
  // Go back and fix page numbers (jsPDF doesn't support retroactive footers easily,
  // so we just add footer to current last page)
  drawFooter(doc, totalPages, totalPages);

  // ── Screenshot page (if available) ───────────────────────────────
  if (result.screenshot) {
    doc.addPage();
    doc.setFillColor(...C.bg);
    doc.rect(0, 0, 210, 297, "F");
    drawHeader(doc, result.url, date);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...C.white);
    doc.text("Page Screenshot", 8, 28);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...C.muted);
    doc.text("Captured at 1280×900px during analysis", 8, 35);
    try {
      doc.addImage(
        result.screenshot,
        "JPEG",
        8,
        40,
        W - 16,
        (W - 16) * (900 / 1280),
      );
    } catch {}
    drawFooter(doc, doc.getNumberOfPages(), doc.getNumberOfPages());
  }

  // ── Trigger download ─────────────────────────────────────────────
  const hostname = new URL(result.url).hostname.replace(/[^a-z0-9]/gi, "-");
  const dateStr = new Date(result.analyzedAt).toISOString().slice(0, 10);
  doc.save(`sitescope-${hostname}-${dateStr}.pdf`);
}
