services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHROME_PATH=/usr/bin/google-chrome-stable
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
